# Generated by Django 3.0.4 on 2020-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_load_fixtures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'verbose_name': 'bem permanente', 'verbose_name_plural': 'bens permanentes'},
        ),
        migrations.AlterModelOptions(
            name='historicoestoque',
            options={'ordering': ('-data_hora',), 'verbose_name': 'Evento de Estoque', 'verbose_name_plural': 'Movimentação no Estoque de Bens de Consumo'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('nome',), 'verbose_name': 'item', 'verbose_name_plural': 'classe de itens'},
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observação relevante sobre a bem', max_length=400, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Indefinido'), (1, 'Ativo'), (2, 'Inativo')], db_index=True, default=1, help_text='Situação do bem', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='tombo',
            field=models.CharField(help_text='Número patrimônial do bem', max_length=10, unique=True, verbose_name='Tombo'),
        ),
    ]
